name: publish

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            extra-arch: ia32
          - os: windows-latest
            extra-arch: ia32
          - os: macos-latest
            extra-arch: ''

    name: build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install gcc-multilib
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install g++-multilib -y

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Set package version
        shell: bash
        run: npm --no-git-tag-version version "${GITHUB_REF_NAME#v}"

      - name: Install npm dependencies
        run: npm ci --ignore-scripts

      - name: Build host artifact
        run: npm run build

      - name: Run tests
        run: npm run test -- --runInBand

      - name: Build additional artifact
        if: matrix.extra-arch != ''
        run: npm run build:native -- --target_arch=${{ matrix.extra-arch }}

      - name: Upload to release
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "${GITHUB_REF_NAME}" packages/utimes*.tar.gz --clobber

  build-arm:
    strategy:
      matrix:
        arch: [aarch64, armv7]
        distro: [ubuntu22.04]

    name: build ${{ matrix.distro }}:${{ matrix.arch }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set package version
        shell: bash
        run: npm --no-git-tag-version version "${GITHUB_REF_NAME#v}"

      - name: Build artifact (${{ matrix.arch }})
        uses: uraimo/run-on-arch-action@v2.1.1
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          dockerRunArgs: --volume "${PWD}:/repo"
          install: |
            apt-get update -y
            apt-get install -y curl
            curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
            apt-get install -y make g++ python nodejs
          run: |
            cd /repo
            npm ci --ignore-scripts
            npm run build
            npm run test -- --runInBand

      - name: Upload to release
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "${GITHUB_REF_NAME}" packages/utimes*.tar.gz --clobber

  publish:
    needs: [build, build-arm]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          registry-url: https://registry.npmjs.org

      - name: Set package version
        shell: bash
        run: npm --no-git-tag-version version "${GITHUB_REF_NAME#v}"

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run checks
        run: npm run check

      - name: Publish to npm
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
